#!/bin/bash

# SYNTAX: make_setupdirs MAX_ID


root_dir=$(pwd)
scripts_dir=$(dirname $(readlink $0 -f))
setups_dir=$root_dir/setups

# make dirs
mkdir -p $setups_dir
$scripts_dir/make_subdirs $setups_dir $1
