#!/usr/bin/env python

###############################################################################
# This script generates the Hamiltonian for a multi-component 1D system.
###############################################################################


import os

# import Hamiltonian
from hamiltonian import get_hamiltonian

## create many-body Hamiltonian and write it to a file
hamilt = get_hamiltonian()
hamilt.createOperatorFileb("hamiltonian.dat")
